---
- name: Deploying GitLab runner in openSUSE 15.1
  hosts: runner
  remote_user: "{{ runner_host_user }}"
  become: yes
  become_user: root
  roles:
    - common
    - docker
    - runner
    - node-exporter
