---
# tasks file for docker
- name: Install Docker from repository
  zypper:
    name:
        - docker
    state: present
  when: ansible_os_family == "Suse"

- name: Install Docker for Debian based
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install docker-compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-{{ansible_system}}-{{ansible_architecture}}"
    dest: /usr/bin/docker-compose
    mode: +x

- name: Add docker exporter
  template:
      src: daemon.j2
      dest: /etc/docker/daemon.json
  when: additional.docker_exporter.deploy

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
  notify: restart docker

- name: Check if Ctop is installed
  stat:
      path: /usr/local/bin/ctop
  register: ctop_path

- name: Install Ctop for monitoring running container
  get_url:
      url: https://github.com/bcicen/ctop/releases/download/v{{ additional.ctop.version }}/ctop-{{ additional.ctop.version }}-linux-{{ additional.ctop.arch }}
      dest: /usr/local/bin/ctop
      mode: 0755
      remote_src: yes
  when:  additional.ctop.deploy and ctop_path.stat.exists == False
