---
# tasks file for docker
- name: Install Docker from repository
  zypper:
    name:
        - docker
        - docker-compose
    state: present

- name: Enable docker service
  systemd:
    name: docker
    enabled: yes
  notify: restart docker
