---
# tasks file for common
- name: Install NTP package from repository
  zypper:
    name:
        - ntp
    state: present
  when: ansible_os_family == "Suse"

- name: Install NTP package from repository
  apt:
    name:
        - ntp
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Set timezone to Asia/Jakarta
  timezone:
    name: "{{ runner_timezone }}"

- name: Check if hostname is configured
  shell: >
      hostname
  register: current_hostname
  changed_when: False

- name: Set hostname to {{ inventory_hostname }} respectively
  shell: >
      hostnamectl set-hostname {{ inventory_hostname }}
  when: current_hostname.stdout != inventory_hostname

- name: Set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ inventory_hostname }}"
    line: "{{ ansible_host }} {{ inventory_hostname }}"
    state: present
