---
# tasks file for common
- name: Set timezone to Asia/Jakarta
  timezone:
    name: Asia/Jakarta

- name: Check if hostname is configured
  shell: >
      hostname -f
  register: current_hostname
  changed_when: False

- name: Set hostname to {{ inventory_hostname }}
  shell: >
      hostnamectl set-hostname {{ inventory_hostname }}
  when: current_hostname.stdout != inventory_hostname

- name: Set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ inventory_hostname }}"
    line: 127.0.0.1 {{ inventory_hostname }}
    state: present
