---
# handlers file for node-exporter
- name: Reload systemd daemon
  systemd:
      daemon_reload: yes

- name: Restart node_exporter
  systemd:
      name: node_exporter
      state: restarted
      force: yes
