---
# tasks file for register-runner
- name: List configured runners
  shell: >
    {{ runner_path }} list
  register: configured_runners
  changed_when: False

- name: Register runner to GitLab
  shell: >
    {{ runner_path }} register
    --non-interactive
    --url '{{ runner_coordinator_url }}'
    --registration-token '{{ runner_registration_token }}'
    --description '{{ runner_description }} {{ inventory_hostname }}'
    --tag-list '{{ runner_tags | join(",") }}'
    --executor '{{ runner_executor }}'
    --docker-image '{{ runner_docker_image }}'
  when: configured_runners.stderr.find('\n runner_description ') == -1
  notify: Restart the runner
