---
# handlers file for runner
- name: check if gitlab-runner executable is present
  stat:
      path: >
        "{{ runner_path }}"
  register: runner_present
  changed_when: False

- name: List configured runners
  shell: >
   "{{ runner_path }}" list
  register: configured_runners
  changed_when: False

- name: Start gitlab-runner
  systemd:
    name: gitlab-runner
    state: started
  when: runner_present.stat.exists == True

- name: Force restart the runner
  systemd:
    name: gitlab-runner
    state: restarted
    # force: yes

- name: Restart the runner
  systemd:
    name: gitlab-runner
    state: restarted
