---
# handlers file for runner
- name: check if gitlab-runner is present
  stat:
      path: >
        "{{ runner_path }}"
  register: runner_present
  changed_when: False

- name: List configured runners
  shell: >
   "{{ runner_path }}" list
  register: configured_runners
  changed_when: False

- name: start gitlab-runner
  shell: >
    "{{ runner_path }}" start
  when: runner_present.stat.exists == True

- name: Restart the runner
  shell: >
    "{{ runner_path }}" restart
  when: configured_runners.stderr.find('\n runner_description') == -1
